name: update_run

on:
  schedule:
    - cron: '*/5 * * * *' 
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python '3.9'
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: execute the code
      run: python update_number.py
    - name: commit files
      run: |
          git config --local user.name "sasikanth300789"
          git config --local user.email sasikanth.nagalla2683@gmail.com
          git add --all
          git commit -am "updated data at $(date +"%D %T")"
          git push origin main --force
      env:
        REPO_KEY: ${{ secrets.GITHUB_TOKEN }}
        username: github-actions
