name: update_run

on:
  schedule:
    - cron: '* * * * *' 
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python '3.9'
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: execute the code
      run: python update_number.py
    - name: commit files
      run: |
          git config user.name "sasikanth300789"
          git config user.email sasikanth.nagalla2683@gmail.com
          git commit -m "updated"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
